# Generated by Django 4.2.7 on 2025-08-06 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secuencias",
            name="sistema",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sistema_nombre",
                to="Secuencias.sistema",
                verbose_name="Sistema",
            ),
        ),
    ]
