# Generated by Django 4.2.7 on 2025-08-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Protocolo_Metodos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolos",
            name="entregado_a",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Entregado a"
            ),
        ),
        migrations.AddField(
            model_name="protocolos",
            name="fecha_de_entrega",
            field=models.DateField(
                help_text="AAAA/MM/DD", null=True, verbose_name="Fecha de Entrega"
            ),
        ),
    ]
